name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v2
      - run: pip install joblib
      - run: pip install sklearn
      - run: python test_model.py
      - run: pip install streamlit
      - run: pip install -U Jinja2
      - run: streamlit run model_dashboard.py &
      - run: npm install -g n
      - run: npm install cypress
      - run: npx cypress open &
      - name: Cypress run
        uses: cypress-io/github-action@v4